name: ci

on: [push, pull_request]

jobs:

  linuxMeson:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: python -m pip install meson
    - run: sudo apt install -yq --no-install-recommends ninja-build gfortran g++
    - run: meson setup build
      env:
        FC: gfortran
    - run: meson test -C build -v
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Linux_Meson_Testlog
        path: build/meson-logs/testlog.txt

  macosMeson:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: brew install gcc ninja
    - run: pip install meson
    - run: meson setup build
      env:
        FC: gfortran
    - run: meson test -C build -v
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: MacOS_Meson_Testlog
        path: build/meson-logs/testlog.txt

  windowsMeson:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: cinst -y mingw ninja
    - run: pip install meson
    - run: meson setup build
      env:
        FC: gfortran
    - run: meson test -C build -v
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Windows_Meson_Testlog
        path: build/meson-logs/testlog.txt

  windowsCmake:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - run: cmake -B build -G "MinGW Makefiles" -DCMAKE_SH="CMAKE_SH-NOTFOUND"
      env:
        FC: gfortran
    - run: cmake --build build --parallel
    - run: ctest -V
      working-directory: build
